#+title: My Dotfiles

This is a collection of my dotfiles I use on my main system.

I manage my dotfiles using a *Git bare repository*. A setup guide for this method can be found [[https://www.atlassian.com/git/tutorials/dotfiles][here]].

* Contents

+ AwesomeWM
+ Bash
+ Btop (theming)
+ Emacs/[[https://github.com/doomemacs/doomemacs][Doom Emacs]]
+ Flameshot
+ Kitty
+ Picom
+ Rofi

* Installation

Clone the bare repository.

#+begin_src bash
    git clone --bare git@github.com:Thomsn1337/dotfiles.git ~/.dotfiles
#+end_src

Create a temporary alias in your current shell scope to access the repository.

#+begin_src bash
    alias dots='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
#+end_src

Configure the bare repository to ignore untracked files.

#+begin_src bash
    dots config --local status.showUntrackedFiles no
#+end_src

Checkout the content of the repository.

#+begin_src bash
    dots checkout
#+end_src

This last step might fail because of existing config files. Delete them or back them up if needed and repeat this step.

* System-wide configs

The ~misc~ folder contains some system-wide configs and a package list of all required packages. Right now, they have to be installed manually. Instructions can be found in ~setup.org~.

+ [ ] Setup script
