add_newline = true

[username]
format = " [$user]($style)@"
style_user = "bold #ed8796"
style_root = "bold #ed8796"
show_always = true

[hostname]
format = "[$hostname]($style) in "
style = "bold #f5a97f"
disabled = false
ssh_only = false

[directory]
format = "[$path]($style) [$read_only]($read_only_style)"
style = "#c6a0f6"

[character]
success_symbol = " [той ](#a6da95)"
error_symbol = " [той ](#ed8796)"

[cmd_duration]
disabled = true
